Repository OCamlPro/superbol-studio-oss, pull requests merged in 2024-03, with the labels that each got.

#182 Filter out LSP diagnostics for dialects other than COBOL85
  README.md
  src/lsp/cobol_lsp/lsp_server.ml
  src/lsp/cobol_lsp/lsp_server.mli
  src/lsp/cobol_lsp/lsp_server_loop.ml
  src/lsp/cobol_lsp/lsp_server_loop.mli
  src/lsp/superbol_free_lib/arg_utils.ml
  src/lsp/superbol_free_lib/arg_utils.mli
  src/lsp/superbol_free_lib/command_lsp.ml
  test/lsp/lsp_testing.ml
Labels: ok to review

#183 Prevent inter-mixing typeck and syntax error diagnostics
  src/lsp/cobol_lsp/lsp_document.ml
  test/lsp/lsp_definition.ml
Labels: ok to review

#187 Fix source format of IBM test files
  test/output-tests/preproc.ml
  test/output-tests/reparse.ml
  test/testsuite/ibm/ibmmainframes.com/cob1.cbl
  test/testsuite/ibm/ibmmainframes.com/cob10.cbl
  test/testsuite/ibm/ibmmainframes.com/cob11.cbl
  test/testsuite/ibm/ibmmainframes.com/cob12.cbl
  test/testsuite/ibm/ibmmainframes.com/cob13.cbl
  test/testsuite/ibm/ibmmainframes.com/cob14.cbl
  test/testsuite/ibm/ibmmainframes.com/cob15.cbl
  test/testsuite/ibm/ibmmainframes.com/cob16.cbl
  test/testsuite/ibm/ibmmainframes.com/cob17.cbl
  test/testsuite/ibm/ibmmainframes.com/cob2.cbl
  test/testsuite/ibm/ibmmainframes.com/cob3.cbl
  test/testsuite/ibm/ibmmainframes.com/cob4.cbl
  test/testsuite/ibm/ibmmainframes.com/cob5.cbl
  test/testsuite/ibm/ibmmainframes.com/cob6.cbl
  test/testsuite/ibm/ibmmainframes.com/cob7.cbl
  test/testsuite/ibm/ibmmainframes.com/cob8.cbl
  test/testsuite/ibm/ibmmainframes.com/cob9.cbl
Labels: ok to review

#206 SuperBOL Studio Pack
  README.md
  package.json
  src/lsp/superbol_free_lib/vscode_extension.ml
  studio/CHANGELOG.md
  studio/LICENSE.md
  studio/README.md
  studio/icon.png
  studio/package.json
Labels: ok to review

#207 Try restarting the LSP server upon change of `superbol.lsp-path` setting
  src/vscode/superbol-vscode-platform/superbol_vscode_platform.ml
Labels: enhancement, ok to review, vscode

#214 Fix maximum line length for X/Open free-form source-format
  src/lsp/cobol_preproc/src_format.ml
Labels: bug

#212 Ship GnuCOBOL config files in the VSIX, and use them as fallback
  .drom
  .gitignore
  .vscodeignore
  Makefile.header
  drom.toml
  src/lsp/cobol_config/cobol_config.ml
  src/vscode/superbol-vscode-platform/superbol_instance.ml
  src/vscode/superbol-vscode-platform/superbol_instance.mli
  src/vscode/superbol-vscode-platform/superbol_languageclient.ml
  src/vscode/superbol-vscode-platform/superbol_languageclient.mli
  src/vscode/superbol-vscode-platform/superbol_vscode_platform.ml
Labels: ok to review

#213 Add flag to force reporting of syntax diagnostics
  README.md
  package.json
  src/lsp/superbol_free_lib/vscode_extension.ml
  src/vscode/superbol-vscode-platform/superbol_instance.ml
  src/vscode/superbol-vscode-platform/superbol_languageclient.ml
  src/vscode/superbol-vscode-platform/superbol_languageclient.mli
  src/vscode/superbol-vscode-platform/superbol_vscode_platform.ml
Labels: ok to review

#177 Add CHAINING keyword in grammar
  src/lsp/cobol_lsp/lsp_semtoks.ml
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_ptree/proc_division.ml
  src/lsp/cobol_ptree/proc_division_visitor.ml
  test/output-tests/run_extensions.expected
  test/output-tests/run_file.expected
  test/output-tests/run_misc.expected
Labels: ok to review

#200 Use syntax file for colorization of text that miss semantic tokens
  package.json
  src/lsp/cobol_lsp/lsp_request.ml
  src/lsp/superbol_free_lib/vscode_extension.ml
  src/vscode/vscode-json/manifest.ml
  syntaxes/COBOL.tmLanguage.json
  test/lsp/lsp_hover.ml
Labels: ok to review

#204 Harden the LSP server against requests about copybook documents
  src/lsp/cobol_lsp/lsp_request.ml
Labels: ok to review, lsp-server

#210 Support dynamic addition/removal of workspace folders
  src/lsp/cobol_lsp/lsp_capabilities.ml
  src/lsp/cobol_lsp/lsp_notif.ml
  src/lsp/cobol_lsp/lsp_server.ml
  src/lsp/cobol_lsp/lsp_server.mli
Labels: ok to review, lsp-server

#218 Partial implementation of conditional compilation
  .drom
  dune-project
  opam/cobol_preproc.opam
  opam/osx/cobol_preproc-osx.opam
  opam/windows/cobol_preproc-windows.opam
  src/lsp/cobol_data/cobol_data.ml
  src/lsp/cobol_data/data_diagnostics.ml
  src/lsp/cobol_data/data_literal.ml
  src/lsp/cobol_data/data_literal_lexer.mll
  src/lsp/cobol_data/dune
  src/lsp/cobol_data/package.toml
  src/lsp/cobol_indent_old/indenter.ml
  src/lsp/cobol_lsp/lsp_request.ml
  src/lsp/cobol_lsp/lsp_semtoks.ml
  src/lsp/cobol_parser/text_tokenizer.ml
  src/lsp/cobol_preproc/cobol_preproc.ml
  src/lsp/cobol_preproc/compdir_grammar.mly
  src/lsp/cobol_preproc/compdir_keywords.ml
  src/lsp/cobol_preproc/compdir_tree.ml
  src/lsp/cobol_preproc/dune
  src/lsp/cobol_preproc/package.toml
  src/lsp/cobol_preproc/preproc_diagnostics.ml
  src/lsp/cobol_preproc/preproc_directives.ml
  src/lsp/cobol_preproc/preproc_engine.ml
  src/lsp/cobol_preproc/preproc_env.ml
  src/lsp/cobol_preproc/preproc_logic.ml
  src/lsp/cobol_preproc/preproc_options.ml
  src/lsp/cobol_preproc/preproc_trace.ml
  src/lsp/cobol_preproc/preproc_trace.mli
  src/lsp/cobol_preproc/src_format.ml
  src/lsp/cobol_preproc/src_format.mli
  src/lsp/cobol_preproc/src_lexer.mli
  src/lsp/cobol_preproc/src_lexer.mll
  src/lsp/cobol_preproc/src_reader.ml
  src/lsp/cobol_preproc/src_reader.mli
  src/lsp/cobol_preproc/src_tokenizer.ml
  src/lsp/cobol_preproc/src_tokenizer.mli
  src/lsp/superbol_free_lib/common_args.ml
  test/cobol_parsing/parser_testing.ml
  test/cobol_preprocessing/compiler_directives.ml
  test/cobol_preprocessing/preproc_testing.ml
  test/output-tests/data_binary.expected
  test/output-tests/data_display.expected
  test/output-tests/data_packed.expected
  test/output-tests/listings.expected
  test/output-tests/preproc.ml
  test/output-tests/run_accept.expected
  test/output-tests/run_extensions.expected
  test/output-tests/run_file.expected
  test/output-tests/run_functions.expected
  test/output-tests/run_fundamental.expected
  test/output-tests/run_misc.expected
  test/output-tests/run_ml.expected
  test/output-tests/run_refmod.expected
  test/output-tests/syn_misc.expected
Labels: ok to review

#221 Add support for `LENGTH OF` expressions
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_parser/grammar_context.ml
  src/lsp/cobol_parser/grammar_post_actions.ml
  src/lsp/cobol_parser/grammar_printer.ml
  src/lsp/cobol_parser/grammar_recover.ml
  src/lsp/cobol_ptree/terms.ml
  src/lsp/cobol_ptree/terms_visitor.ml
  test/output-tests/run_extensions.expected
  test/output-tests/run_file.expected
  test/output-tests/run_misc.expected
  test/output-tests/syn_definition.expected
Labels: enhancement, ok to review

#222 Handle `COMMON` keyword in `PROGRAM-ID`
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_ptree/compilation_group.ml
  src/lsp/cobol_ptree/compilation_group_visitor.ml
  test/output-tests/syn_definition.expected
Labels: bug, ok to review

#228 Fix INSPECT TALLYING FOR ALL CHARACTERS
  src/lsp/cobol_parser/grammar.mly
Labels: bug, ok to review

#238 Handle RECORDING MODE in FILE SECTION
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_parser/grammar_tokens.mly
  src/lsp/cobol_ptree/data_descr.ml
  src/lsp/cobol_ptree/data_descr_visitor.ml
  src/lsp/cobol_ptree/data_sections.ml
  src/lsp/cobol_ptree/data_sections_visitor.ml
  test/output-tests/run_reportwriter.expected
Labels: bug, ok to review

#239 Fix ALTERNATE clause of SELECT statement
  src/lsp/cobol_parser/grammar.mly
  test/output-tests/syn_file.expected
Labels: bug, ok to review

#232 Handle ENTRY statement
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_ptree/branching_statements.ml
  src/lsp/cobol_ptree/simple_statements.ml
  src/lsp/cobol_ptree/statements_visitor.ml
  test/output-tests/run_extensions.expected
  test/output-tests/run_fundamental.expected
  test/output-tests/run_misc.expected
Labels: bug, ok to review

#250 Simplify handling of RECORDING MODE clause
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_ptree/data_descr.ml
  src/lsp/cobol_ptree/data_descr_visitor.ml
  src/lsp/cobol_ptree/data_sections.ml
  src/lsp/cobol_ptree/data_sections_visitor.ml
Labels: ok to review

#247 Add GO TO ENTRY statement
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_ptree/branching_statements.ml
  src/lsp/cobol_ptree/statements_visitor.ml
  test/output-tests/run_misc.expected
Labels: bug, ok to review

#253 Extend STOP statement following GnuCOBOL syntax
  src/lsp/cobol_parser/grammar.mly
  src/lsp/cobol_ptree/simple_statements.ml
  src/lsp/cobol_ptree/statements_visitor.ml
  test/output-tests/run_extensions.expected
  test/output-tests/run_file.expected
  test/output-tests/run_misc.expected
  test/output-tests/syn_definition.expected
  test/output-tests/syn_misc.expected
  test/output-tests/used_binaries.expected
Labels: ok to review

#254 Fix optional IS in RECORDING MODE
  src/lsp/cobol_parser/grammar.mly
  test/output-tests/reparse.expected
Labels: ok to review
