Repository OCamlPro/superbol-studio-oss, pull requests merged in 2024-02, with the labels that each got.

#155 Bugfix: upon rewind, clear source overlay locations cache earlier
  src/lsp/cobol_parser/parser_engine.ml
  src/lsp/cobol_preproc/src_overlay.ml
  src/lsp/cobol_preproc/src_overlay.mli
  src/lsp/cobol_preproc/text_supplier.ml
Labels: bug, ok to review

#163 Fix source locations of data division's sections
  src/lsp/cobol_parser/grammar.mly
Labels: ok to review

#162 Fix lookup when `COPY <text-name> IN/OF <relative path>` is used
  src/lsp/cobol_common/copybook.ml
  src/lsp/cobol_common/copybook.mli
  src/lsp/cobol_preproc/preproc_directives.ml
  src/lsp/cobol_preproc/preproc_engine.ml
  src/lsp/cobol_preproc/preproc_engine.mli
  src/lsp/cobol_preproc/preproc_grammar.mly
  src/lsp/cobol_preproc/src_input.ml
  src/lsp/cobol_preproc/src_reader.ml
  src/lsp/cobol_preproc/src_reader.mli
  test/output-tests/syn_copy.expected
  test/output-tests/used_binaries.expected
Labels: bug, ok to review

#158 Make goto-def and find-refs return locations within copybooks
  src/lsp/cobol_lsp/lsp_diagnostics.ml
  src/lsp/cobol_lsp/lsp_diagnostics.mli
  src/lsp/cobol_lsp/lsp_position.ml
  src/lsp/cobol_lsp/lsp_position.mli
  src/lsp/cobol_lsp/lsp_project.ml
  src/lsp/cobol_lsp/lsp_request.ml
  src/lsp/cobol_lsp/lsp_request.mli
  src/lsp/cobol_lsp/lsp_server.ml
Labels: enhancement, ok to review

#160 Harden the LSP against copied source locations in pre-processor logs
  src/lsp/cobol_lsp/lsp_request.ml
Labels: bug, ok to review

#168 Better handle config lookup on Windose
  src/lsp/cobol_config/cobol_config.ml
Labels: bug, ok to review

#169 Add check syntax command
  src/lsp/superbol_free_lib/command_check_syntax.ml
  src/lsp/superbol_free_lib/main.ml
Labels: ok to review

#165 Manifest improvements
  .vscodeignore
  package.json
  schemas/superbol-schema.json
  src/lsp/superbol_free_lib/vscode_extension.ml
  src/vscode/vscode-json/manifest.ml
Labels: enhancement, ok to review

#170 Smoother config management
  src/lsp/cobol_lsp/lsp_project.ml
  src/lsp/cobol_lsp/lsp_project.mli
  src/lsp/cobol_lsp/lsp_request.ml
  src/lsp/cobol_lsp/lsp_server.ml
  src/lsp/cobol_lsp/lsp_server.mli
  src/lsp/superbol_project/project.mli
  src/lsp/superbol_project/project_config.ml
  src/lsp/superbol_project/project_config.mli
  src/vscode/superbol-vscode-platform/superbol_commands.ml
  src/vscode/superbol-vscode-platform/superbol_instance.ml
Labels: ok to review
